In [1]:
!pip install celltypist

Collecting celltypist
  Downloading celltypist-1.7.1-py3-none-any.whl.metadata (45 kB)
     ---------------------------------------- 0.0/45.1 kB ? eta -:--:--
     --------- ------------------------------ 10.2/45.1 kB ? eta -:--:--
     ----------------- -------------------- 20.5/45.1 kB 217.9 kB/s eta 0:00:01
     ---------------------------------- --- 41.0/45.1 kB 281.8 kB/s eta 0:00:01
     -------------------------------------- 45.1/45.1 kB 248.9 kB/s eta 0:00:00
Requirement already satisfied: numpy>=1.19.0 in d:\anaconda_redo\lib\site-packages (from celltypist) (2.1.3)
Requirement already satisfied: pandas>=1.0.5 in d:\anaconda_redo\lib\site-packages (from celltypist) (2.2.3)
Requirement already satisfied: scikit-learn>=0.24.1 in d:\anaconda_redo\lib\site-packages (from celltypist) (1.6.1)
Requirement already satisfied: openpyxl>=3.0.4 in d:\anaconda_redo\lib\site-packages (from celltypist) (3.1.5)
Requirement already satisfied: click>=7.1.2 in d:\anaconda_redo\lib\site-packages (from celltypist) (8.1.8)
Requirement already satisfied: requests>=2.23.0 in d:\anaconda_redo\lib\site-packages (from celltypist) (2.32.3)
Requirement already satisfied: scanpy>=1.7.0 in d:\anaconda_redo\lib\site-packages (from celltypist) (1.12)
Requirement already satisfied: leidenalg>=0.9.0 in d:\anaconda_redo\lib\site-packages (from celltypist) (0.12.0)
Requirement already satisfied: colorama in d:\anaconda_redo\lib\site-packages (from click>=7.1.2->celltypist) (0.4.6)
Requirement already satisfied: igraph<2.0,>=1.0.0 in d:\anaconda_redo\lib\site-packages (from leidenalg>=0.9.0->celltypist) (1.0.0)
Requirement already satisfied: et-xmlfile in d:\anaconda_redo\lib\site-packages (from openpyxl>=3.0.4->celltypist) (1.1.0)
Requirement already satisfied: python-dateutil>=2.8.2 in d:\anaconda_redo\lib\site-packages (from pandas>=1.0.5->celltypist) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in d:\anaconda_redo\lib\site-packages (from pandas>=1.0.5->celltypist) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in d:\anaconda_redo\lib\site-packages (from pandas>=1.0.5->celltypist) (2025.2)
Requirement already satisfied: charset-normalizer<4,>=2 in d:\anaconda_redo\lib\site-packages (from requests>=2.23.0->celltypist) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in d:\anaconda_redo\lib\site-packages (from requests>=2.23.0->celltypist) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in d:\anaconda_redo\lib\site-packages (from requests>=2.23.0->celltypist) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in d:\anaconda_redo\lib\site-packages (from requests>=2.23.0->celltypist) (2025.4.26)
Requirement already satisfied: anndata>=0.10.8 in d:\anaconda_redo\lib\site-packages (from scanpy>=1.7.0->celltypist) (0.12.10)
Requirement already satisfied: fast-array-utils>=1.2.1 in d:\anaconda_redo\lib\site-packages (from fast-array-utils[accel,sparse]>=1.2.1->scanpy>=1.7.0->celltypist) (1.4)
Requirement already satisfied: h5py>=3.11 in d:\anaconda_redo\lib\site-packages (from scanpy>=1.7.0->celltypist) (3.12.1)
Requirement already satisfied: joblib in d:\anaconda_redo\lib\site-packages (from scanpy>=1.7.0->celltypist) (1.4.2)
Requirement already satisfied: legacy-api-wrap>=1.5 in d:\anaconda_redo\lib\site-packages (from scanpy>=1.7.0->celltypist) (1.5)
Requirement already satisfied: matplotlib>=3.9 in d:\anaconda_redo\lib\site-packages (from scanpy>=1.7.0->celltypist) (3.10.0)
Requirement already satisfied: natsort in d:\anaconda_redo\lib\site-packages (from scanpy>=1.7.0->celltypist) (8.4.0)
Requirement already satisfied: networkx>=2.8.8 in d:\anaconda_redo\lib\site-packages (from scanpy>=1.7.0->celltypist) (3.4.2)
Requirement already satisfied: numba>=0.60 in d:\anaconda_redo\lib\site-packages (from scanpy>=1.7.0->celltypist) (0.61.0)
Requirement already satisfied: packaging>=25 in d:\anaconda_redo\lib\site-packages (from scanpy>=1.7.0->celltypist) (26.0)
Requirement already satisfied: patsy in d:\anaconda_redo\lib\site-packages (from scanpy>=1.7.0->celltypist) (1.0.1)
Requirement already satisfied: pynndescent>=0.5.13 in d:\anaconda_redo\lib\site-packages (from scanpy>=1.7.0->celltypist) (0.6.0)
Requirement already satisfied: scipy>=1.13 in d:\anaconda_redo\lib\site-packages (from scanpy>=1.7.0->celltypist) (1.13.1)
Requirement already satisfied: seaborn>=0.13.2 in d:\anaconda_redo\lib\site-packages (from scanpy>=1.7.0->celltypist) (0.13.2)
Requirement already satisfied: session-info2 in d:\anaconda_redo\lib\site-packages (from scanpy>=1.7.0->celltypist) (0.4)
Requirement already satisfied: statsmodels>=0.14.5 in d:\anaconda_redo\lib\site-packages (from scanpy>=1.7.0->celltypist) (0.14.6)
Requirement already satisfied: tqdm in d:\anaconda_redo\lib\site-packages (from scanpy>=1.7.0->celltypist) (4.67.1)
Requirement already satisfied: typing-extensions in d:\anaconda_redo\lib\site-packages (from scanpy>=1.7.0->celltypist) (4.15.0)
Requirement already satisfied: umap-learn>=0.5.7 in d:\anaconda_redo\lib\site-packages (from scanpy>=1.7.0->celltypist) (0.5.11)
Requirement already satisfied: threadpoolctl>=3.1.0 in d:\anaconda_redo\lib\site-packages (from scikit-learn>=0.24.1->celltypist) (3.5.0)
Requirement already satisfied: array-api-compat>=1.7.1 in d:\anaconda_redo\lib\site-packages (from anndata>=0.10.8->scanpy>=1.7.0->celltypist) (1.14.0)
Requirement already satisfied: zarr!=3.0.*,>=2.18.7 in d:\anaconda_redo\lib\site-packages (from anndata>=0.10.8->scanpy>=1.7.0->celltypist) (3.1.6)
Requirement already satisfied: texttable>=1.6.2 in d:\anaconda_redo\lib\site-packages (from igraph<2.0,>=1.0.0->leidenalg>=0.9.0->celltypist) (1.7.0)
Requirement already satisfied: contourpy>=1.0.1 in d:\anaconda_redo\lib\site-packages (from matplotlib>=3.9->scanpy>=1.7.0->celltypist) (1.3.1)
Requirement already satisfied: cycler>=0.10 in d:\anaconda_redo\lib\site-packages (from matplotlib>=3.9->scanpy>=1.7.0->celltypist) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in d:\anaconda_redo\lib\site-packages (from matplotlib>=3.9->scanpy>=1.7.0->celltypist) (4.55.3)
Requirement already satisfied: kiwisolver>=1.3.1 in d:\anaconda_redo\lib\site-packages (from matplotlib>=3.9->scanpy>=1.7.0->celltypist) (1.4.8)
Requirement already satisfied: pillow>=8 in d:\anaconda_redo\lib\site-packages (from matplotlib>=3.9->scanpy>=1.7.0->celltypist) (11.1.0)
Requirement already satisfied: pyparsing>=2.3.1 in d:\anaconda_redo\lib\site-packages (from matplotlib>=3.9->scanpy>=1.7.0->celltypist) (3.2.0)
Requirement already satisfied: llvmlite<0.45,>=0.44.0dev0 in d:\anaconda_redo\lib\site-packages (from numba>=0.60->scanpy>=1.7.0->celltypist) (0.44.0)
Requirement already satisfied: six>=1.5 in d:\anaconda_redo\lib\site-packages (from python-dateutil>=2.8.2->pandas>=1.0.5->celltypist) (1.17.0)
Requirement already satisfied: donfig>=0.8 in d:\anaconda_redo\lib\site-packages (from zarr!=3.0.*,>=2.18.7->anndata>=0.10.8->scanpy>=1.7.0->celltypist) (0.8.1.post1)
Requirement already satisfied: google-crc32c>=1.5 in d:\anaconda_redo\lib\site-packages (from zarr!=3.0.*,>=2.18.7->anndata>=0.10.8->scanpy>=1.7.0->celltypist) (1.8.0)
Requirement already satisfied: numcodecs>=0.14 in d:\anaconda_redo\lib\site-packages (from zarr!=3.0.*,>=2.18.7->anndata>=0.10.8->scanpy>=1.7.0->celltypist) (0.16.5)
Requirement already satisfied: pyyaml in d:\anaconda_redo\lib\site-packages (from donfig>=0.8->zarr!=3.0.*,>=2.18.7->anndata>=0.10.8->scanpy>=1.7.0->celltypist) (6.0.2)
Downloading celltypist-1.7.1-py3-none-any.whl (7.3 MB)
   ---------------------------------------- 0.0/7.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/7.3 MB 1.3 MB/s eta 0:00:06
    --------------------------------------- 0.1/7.3 MB 1.6 MB/s eta 0:00:05
   - -------------------------------------- 0.2/7.3 MB 2.9 MB/s eta 0:00:03
   -- ------------------------------------- 0.5/7.3 MB 3.9 MB/s eta 0:00:02
   ------ --------------------------------- 1.1/7.3 MB 6.4 MB/s eta 0:00:01
   -------- ------------------------------- 1.5/7.3 MB 6.7 MB/s eta 0:00:01
   ---------- ----------------------------- 1.9/7.3 MB 7.6 MB/s eta 0:00:01
   ----------- ---------------------------- 2.2/7.3 MB 7.3 MB/s eta 0:00:01
   -------------- ------------------------- 2.7/7.3 MB 8.2 MB/s eta 0:00:01
   ----------------- ---------------------- 3.3/7.3 MB 9.0 MB/s eta 0:00:01
   --------------------- ------------------ 4.0/7.3 MB 9.8 MB/s eta 0:00:01
   ----------------------- ---------------- 4.3/7.3 MB 9.4 MB/s eta 0:00:01
   -------------------------- ------------- 4.8/7.3 MB 9.8 MB/s eta 0:00:01
   ----------------------------- ---------- 5.4/7.3 MB 10.4 MB/s eta 0:00:01
   ------------------------------ --------- 5.6/7.3 MB 10.0 MB/s eta 0:00:01
   -------------------------------- ------- 5.9/7.3 MB 9.9 MB/s eta 0:00:01
   -------------------------------- ------- 5.9/7.3 MB 9.9 MB/s eta 0:00:01
   -------------------------------- ------- 5.9/7.3 MB 9.9 MB/s eta 0:00:01
   ---------------------------------------  7.3/7.3 MB 10.4 MB/s eta 0:00:01
   ---------------------------------------  7.3/7.3 MB 10.4 MB/s eta 0:00:01
   ---------------------------------------- 7.3/7.3 MB 9.6 MB/s eta 0:00:00
Installing collected packages: celltypist
Successfully installed celltypist-1.7.1

In [2]:
import scanpy as sc

adata = sc.read_h5ad(
    r"D:\aer\GSE159677_processed.h5ad"
)

In [ ]:
"""
There were issues with installing celltypist and scanpy.
Something along the lines of version being different in each environment hence the error.
The goal now is to fix it by check the versions of the packages in use.
"""

In [3]:
import numpy
print(numpy.__version__)

2.1.3

In [4]:
import sys
print(sys.executable)

D:\Anaconda_redo\python.exe

In [5]:
import pandas as pd
print(pd.__version__)

2.2.3

In [6]:
import h5py
print(h5py.__version__)

3.12.1

In [7]:
import pyarrow
print(pyarrow.__version__)

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.1.3 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "D:\Anaconda_redo\Lib\runpy.py", line 198, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\Anaconda_redo\Lib\runpy.py", line 88, in _run_code
    exec(code, run_globals)
  File "D:\Anaconda_redo\Lib\site-packages\ipykernel_launcher.py", line 18, in <module>
    app.launch_new_instance()
  File "D:\Anaconda_redo\Lib\site-packages\traitlets\config\application.py", line 1075, in launch_instance
    app.start()
  File "D:\Anaconda_redo\Lib\site-packages\ipykernel\kernelapp.py", line 739, in start
    self.io_loop.start()
  File "D:\Anaconda_redo\Lib\site-packages\tornado\platform\asyncio.py", line 211, in start
    self.asyncio_loop.run_forever()
  File "D:\Anaconda_redo\Lib\asyncio\base_events.py", line 641, in run_forever
    self._run_once()
  File "D:\Anaconda_redo\Lib\asyncio\base_events.py", line 1987, in _run_once
    handle._run()
  File "D:\Anaconda_redo\Lib\asyncio\events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "D:\Anaconda_redo\Lib\site-packages\ipykernel\kernelbase.py", line 545, in dispatch_queue
    await self.process_one()
  File "D:\Anaconda_redo\Lib\site-packages\ipykernel\kernelbase.py", line 534, in process_one
    await dispatch(*args)
  File "D:\Anaconda_redo\Lib\site-packages\ipykernel\kernelbase.py", line 437, in dispatch_shell
    await result
  File "D:\Anaconda_redo\Lib\site-packages\ipykernel\ipkernel.py", line 362, in execute_request
    await super().execute_request(stream, ident, parent)
  File "D:\Anaconda_redo\Lib\site-packages\ipykernel\kernelbase.py", line 778, in execute_request
    reply_content = await reply_content
  File "D:\Anaconda_redo\Lib\site-packages\ipykernel\ipkernel.py", line 449, in do_execute
    res = shell.run_cell(
  File "D:\Anaconda_redo\Lib\site-packages\ipykernel\zmqshell.py", line 549, in run_cell
    return super().run_cell(*args, **kwargs)
  File "D:\Anaconda_redo\Lib\site-packages\IPython\core\interactiveshell.py", line 3075, in run_cell
    result = self._run_cell(
  File "D:\Anaconda_redo\Lib\site-packages\IPython\core\interactiveshell.py", line 3130, in _run_cell
    result = runner(coro)
  File "D:\Anaconda_redo\Lib\site-packages\IPython\core\async_helpers.py", line 128, in _pseudo_sync_runner
    coro.send(None)
  File "D:\Anaconda_redo\Lib\site-packages\IPython\core\interactiveshell.py", line 3334, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "D:\Anaconda_redo\Lib\site-packages\IPython\core\interactiveshell.py", line 3517, in run_ast_nodes
    if await self.run_code(code, result, async_=asy):
  File "D:\Anaconda_redo\Lib\site-packages\IPython\core\interactiveshell.py", line 3577, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "C:\Users\scien\AppData\Local\Temp\ipykernel_111264\1159129366.py", line 1, in <module>
    import pyarrow
  File "D:\Anaconda_redo\Lib\site-packages\pyarrow\__init__.py", line 65, in <module>
    import pyarrow.lib as _lib

ImportError:
A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.1.3 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

ImportError: numpy.core.multiarray failed to import

In [ ]:
"""
Now going to check scanpy to make sure pyarrow is the only broken dependency.
"""

In [8]:
import scanpy as sc

In [10]:
print(sc.__version__)

1.12

C:\Users\scien\AppData\Local\Temp\ipykernel_111264\1066563302.py:1: FutureWarning: `__version__` is deprecated, use `importlib.metadata.version('scanpy')` instead
  print(sc.__version__)

In [11]:
!pip install --force-reinstall --no-cache-dir pyarrow

Collecting pyarrow

  WARNING: Failed to remove contents in a temporary directory 'D:\Anaconda_redo\Lib\site-packages\~yarrow'.
  You can safely remove it manually.
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
streamlit 1.45.1 requires packaging<25,>=20, but you have packaging 26.0 which is incompatible.

  Downloading pyarrow-25.0.0-cp312-cp312-win_amd64.whl.metadata (3.0 kB)
Downloading pyarrow-25.0.0-cp312-cp312-win_amd64.whl (27.9 MB)
   ---------------------------------------- 0.0/27.9 MB ? eta -:--:--
   ---------------------------------------- 0.0/27.9 MB ? eta -:--:--
   ---------------------------------------- 0.0/27.9 MB 330.3 kB/s eta 0:01:25
   ---------------------------------------- 0.1/27.9 MB 550.5 kB/s eta 0:00:51
   ---------------------------------------- 0.1/27.9 MB 804.6 kB/s eta 0:00:35
   ---------------------------------------- 0.3/27.9 MB 1.8 MB/s eta 0:00:15
   - -------------------------------------- 0.8/27.9 MB 3.5 MB/s eta 0:00:08
   - -------------------------------------- 1.1/27.9 MB 4.3 MB/s eta 0:00:07
   -- ------------------------------------- 1.7/27.9 MB 5.7 MB/s eta 0:00:05
   -- ------------------------------------- 1.9/27.9 MB 5.8 MB/s eta 0:00:05
   --- ------------------------------------ 2.5/27.9 MB 6.6 MB/s eta 0:00:04
   ---- ----------------------------------- 2.8/27.9 MB 7.3 MB/s eta 0:00:04
   ---- ----------------------------------- 3.3/27.9 MB 7.3 MB/s eta 0:00:04
   ----- ---------------------------------- 3.8/27.9 MB 7.9 MB/s eta 0:00:04
   ----- ---------------------------------- 3.9/27.9 MB 7.8 MB/s eta 0:00:04
   ------ --------------------------------- 4.6/27.9 MB 8.1 MB/s eta 0:00:03
   ------ --------------------------------- 4.9/27.9 MB 8.0 MB/s eta 0:00:03
   ------- -------------------------------- 5.5/27.9 MB 8.5 MB/s eta 0:00:03
   -------- ------------------------------- 5.6/27.9 MB 8.5 MB/s eta 0:00:03
   -------- ------------------------------- 6.1/27.9 MB 8.5 MB/s eta 0:00:03
   --------- ------------------------------ 6.6/27.9 MB 8.8 MB/s eta 0:00:03
   --------- ------------------------------ 6.6/27.9 MB 8.3 MB/s eta 0:00:03
   ---------- ----------------------------- 7.2/27.9 MB 8.5 MB/s eta 0:00:03
   ---------- ----------------------------- 7.6/27.9 MB 8.6 MB/s eta 0:00:03
   ----------- ---------------------------- 7.8/27.9 MB 8.4 MB/s eta 0:00:03
   ----------- ---------------------------- 8.3/27.9 MB 8.7 MB/s eta 0:00:03
   ------------ --------------------------- 8.7/27.9 MB 8.7 MB/s eta 0:00:03
   ------------- -------------------------- 9.2/27.9 MB 9.0 MB/s eta 0:00:03
   ------------- -------------------------- 9.5/27.9 MB 8.8 MB/s eta 0:00:03
   -------------- ------------------------- 10.1/27.9 MB 9.1 MB/s eta 0:00:02
   -------------- ------------------------- 10.5/27.9 MB 10.2 MB/s eta 0:00:02
   --------------- ------------------------ 10.8/27.9 MB 10.4 MB/s eta 0:00:02
   --------------- ------------------------ 10.9/27.9 MB 10.2 MB/s eta 0:00:02
   --------------- ------------------------ 10.9/27.9 MB 10.2 MB/s eta 0:00:02
   ---------------- ----------------------- 11.8/27.9 MB 10.1 MB/s eta 0:00:02
   ----------------- ---------------------- 12.1/27.9 MB 10.1 MB/s eta 0:00:02
   ------------------ --------------------- 12.7/27.9 MB 10.1 MB/s eta 0:00:02
   ------------------ --------------------- 13.0/27.9 MB 9.9 MB/s eta 0:00:02
   ------------------- -------------------- 13.5/27.9 MB 10.2 MB/s eta 0:00:02
   -------------------- ------------------- 14.0/27.9 MB 10.1 MB/s eta 0:00:02
   -------------------- ------------------- 14.4/27.9 MB 10.2 MB/s eta 0:00:02
   --------------------- ------------------ 14.8/27.9 MB 10.2 MB/s eta 0:00:02
   ---------------------- ----------------- 15.4/27.9 MB 10.2 MB/s eta 0:00:02
   ---------------------- ----------------- 15.8/27.9 MB 10.2 MB/s eta 0:00:02
   ----------------------- ---------------- 16.1/27.9 MB 10.6 MB/s eta 0:00:02
   ----------------------- ---------------- 16.6/27.9 MB 10.2 MB/s eta 0:00:02
   ------------------------ --------------- 16.9/27.9 MB 10.4 MB/s eta 0:00:02
   ------------------------ --------------- 17.2/27.9 MB 10.6 MB/s eta 0:00:02
   ------------------------- -------------- 17.6/27.9 MB 10.2 MB/s eta 0:00:02
   ------------------------- -------------- 18.1/27.9 MB 10.6 MB/s eta 0:00:01
   -------------------------- ------------- 18.4/27.9 MB 10.2 MB/s eta 0:00:01
   -------------------------- ------------- 18.6/27.9 MB 10.2 MB/s eta 0:00:01
   --------------------------- ------------ 19.0/27.9 MB 10.1 MB/s eta 0:00:01
   --------------------------- ------------ 19.2/27.9 MB 9.9 MB/s eta 0:00:01
   ---------------------------- ----------- 19.7/27.9 MB 10.1 MB/s eta 0:00:01
   ---------------------------- ----------- 20.0/27.9 MB 9.8 MB/s eta 0:00:01
   ----------------------------- ---------- 20.4/27.9 MB 9.8 MB/s eta 0:00:01
   ----------------------------- ---------- 20.8/27.9 MB 9.9 MB/s eta 0:00:01
   ------------------------------ --------- 21.1/27.9 MB 9.9 MB/s eta 0:00:01
   ------------------------------ --------- 21.5/27.9 MB 10.2 MB/s eta 0:00:01
   ------------------------------- -------- 21.7/27.9 MB 9.8 MB/s eta 0:00:01
   ------------------------------- -------- 22.2/27.9 MB 10.1 MB/s eta 0:00:01
   -------------------------------- ------- 22.5/27.9 MB 9.8 MB/s eta 0:00:01
   -------------------------------- ------- 22.8/27.9 MB 9.6 MB/s eta 0:00:01
   --------------------------------- ------ 23.1/27.9 MB 9.6 MB/s eta 0:00:01
   --------------------------------- ------ 23.4/27.9 MB 9.5 MB/s eta 0:00:01
   ---------------------------------- ----- 23.9/27.9 MB 9.5 MB/s eta 0:00:01
   ---------------------------------- ----- 24.1/27.9 MB 9.4 MB/s eta 0:00:01
   ----------------------------------- ---- 24.5/27.9 MB 9.4 MB/s eta 0:00:01
   ----------------------------------- ---- 24.9/27.9 MB 9.2 MB/s eta 0:00:01
   ------------------------------------ --- 25.3/27.9 MB 9.4 MB/s eta 0:00:01
   ------------------------------------ --- 25.7/27.9 MB 9.2 MB/s eta 0:00:01
   ------------------------------------- -- 26.1/27.9 MB 9.2 MB/s eta 0:00:01
   ------------------------------------- -- 26.5/27.9 MB 9.4 MB/s eta 0:00:01
   -------------------------------------- - 26.9/27.9 MB 9.2 MB/s eta 0:00:01
   ---------------------------------------  27.3/27.9 MB 9.4 MB/s eta 0:00:01
   ---------------------------------------  27.8/27.9 MB 9.5 MB/s eta 0:00:01
   ---------------------------------------- 27.9/27.9 MB 9.5 MB/s eta 0:00:00
Installing collected packages: pyarrow
  Attempting uninstall: pyarrow
    Found existing installation: pyarrow 14.0.2
    Uninstalling pyarrow-14.0.2:
      Successfully uninstalled pyarrow-14.0.2
Successfully installed pyarrow-25.0.0

In [1]:
import pyarrow
print(pyarrow.__version__)

25.0.0

In [ ]:
# All the descrepensies seems to have been resolved back to calling adata

In [2]:
import scanpy as sc

adata = sc.read_h5ad(
    r"D:\aer\GSE159677_processed.h5ad"
)

print(adata)

AnnData object with n_obs × n_vars = 47377 × 2000
    obs: 'sample', 'condition', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_100_genes', 'pct_counts_in_top_200_genes', 'pct_counts_in_top_500_genes', 'total_counts_mt', 'log1p_total_counts_mt', 'pct_counts_mt', 'leiden'
    var: 'highly_variable', 'means', 'dispersions', 'dispersions_norm', 'highly_variable_nbatches', 'highly_variable_intersection', 'mean', 'std'
    uns: 'condition_colors', 'hvg', 'leiden', 'leiden_colors', 'neighbors', 'pca', 'rank_genes_groups', 'sample_colors', 'umap'
    obsm: 'X_pca', 'X_umap'
    varm: 'PCs'
    obsp: 'connectivities', 'distances'

In [3]:
# Just saving an additional check point

adata.write(r"D:\aer\GSE159677_processed_final.h5ad")

In [ ]:
# Now import the package

In [4]:
import celltypist
from celltypist import models

D:\Anaconda_redo\Lib\site-packages\celltypist\classifier.py:11: FutureWarning: `__version__` is deprecated, use `importlib.metadata.version('scanpy')` instead
  from scanpy import __version__ as scv

In [5]:
import celltypist
print(celltypist.__version__)

1.7.1

In [ ]:
# Quick check both files are the same

In [6]:
import scanpy as sc

adata1 = sc.read_h5ad(
    r"D:\aer\GSE159677_processed.h5ad"
)

adata2 = sc.read_h5ad(
    r"D:\aer\GSE159677_processed_final.h5ad"
)

In [7]:
print(adata1)
print(adata2)

AnnData object with n_obs × n_vars = 47377 × 2000
    obs: 'sample', 'condition', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_100_genes', 'pct_counts_in_top_200_genes', 'pct_counts_in_top_500_genes', 'total_counts_mt', 'log1p_total_counts_mt', 'pct_counts_mt', 'leiden'
    var: 'highly_variable', 'means', 'dispersions', 'dispersions_norm', 'highly_variable_nbatches', 'highly_variable_intersection', 'mean', 'std'
    uns: 'condition_colors', 'hvg', 'leiden', 'leiden_colors', 'neighbors', 'pca', 'rank_genes_groups', 'sample_colors', 'umap'
    obsm: 'X_pca', 'X_umap'
    varm: 'PCs'
    obsp: 'connectivities', 'distances'
AnnData object with n_obs × n_vars = 47377 × 2000
    obs: 'sample', 'condition', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_100_genes', 'pct_counts_in_top_200_genes', 'pct_counts_in_top_500_genes', 'total_counts_mt', 'log1p_total_counts_mt', 'pct_counts_mt', 'leiden'
    var: 'highly_variable', 'means', 'dispersions', 'dispersions_norm', 'highly_variable_nbatches', 'highly_variable_intersection', 'mean', 'std'
    uns: 'condition_colors', 'hvg', 'leiden', 'leiden_colors', 'neighbors', 'pca', 'rank_genes_groups', 'sample_colors', 'umap'
    obsm: 'X_pca', 'X_umap'
    varm: 'PCs'
    obsp: 'connectivities', 'distances'

In [ ]:
# Farther check they are the same

In [8]:
adata1.obs.equals(adata2.obs)

True

In [9]:
adata1.var.equals(adata2.var)

True

In [ ]:
# Check whether expression matrices are the same

In [10]:
(adata1.X != adata2.X).nnz

AttributeError: 'numpy.ndarray' object has no attribute 'nnz'

In [ ]:
# Verify

In [11]:
import numpy as np

np.array_equal(adata1.X, adata2.X)

True

In [12]:
np.allclose(adata1.X, adata2.X)

True

In [ ]:
"""
This dataset from the scanpy pipeline has been selected for highly variable genes.
Raw data had 33,538 genes per cell, where highly variable genes has 2000 genes.
Normally cell annotation is done with a larger varity of genes.
First annotation will be attepted on the post highly variable genes dataset.
"""

In [13]:
import scanpy as sc

adata = sc.read_h5ad(
    r"D:\aer\GSE159677_processed_final.h5ad"
)

print(adata)

AnnData object with n_obs × n_vars = 47377 × 2000
    obs: 'sample', 'condition', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_100_genes', 'pct_counts_in_top_200_genes', 'pct_counts_in_top_500_genes', 'total_counts_mt', 'log1p_total_counts_mt', 'pct_counts_mt', 'leiden'
    var: 'highly_variable', 'means', 'dispersions', 'dispersions_norm', 'highly_variable_nbatches', 'highly_variable_intersection', 'mean', 'std'
    uns: 'condition_colors', 'hvg', 'leiden', 'leiden_colors', 'neighbors', 'pca', 'rank_genes_groups', 'sample_colors', 'umap'
    obsm: 'X_pca', 'X_umap'
    varm: 'PCs'
    obsp: 'connectivities', 'distances'

In [14]:
adata.X[:5, :5]

array([[-0.13948631, -0.34477256, -0.6061098 , -0.21292265, -0.23678926],
       [-0.13948631, -0.34477256,  1.5785881 , -0.21292265, -0.23678926],
       [-0.13948631, -0.34477256, -0.6061098 , -0.21292265, -0.23678926],
       [-0.13948631, -0.34477256,  0.45026395, -0.21292265, -0.23678926],
       [-0.13948631, -0.34477256, -0.6061098 , -0.21292265, -0.23678926]])

In [15]:
type(adata.X)

numpy.ndarray

In [ ]:
# View Different Models

In [16]:
from celltypist import models

models.models_description()

👉 Detailed model information can be found at `https://www.celltypist.org/models`
📜 Retrieving model list from server https://celltypist.cog.sanger.ac.uk/models/models.json
📚 Total models in list: 61

,model,description
0,Immune_All_Low.pkl,immune sub-populations combined from 20 tissue...
1,Immune_All_High.pkl,immune populations combined from 20 tissues of...
2,Adult_COVID19_PBMC.pkl,peripheral blood mononuclear cell types from C...
3,Adult_CynomolgusMacaque_Hippocampus.pkl,cell types from the hippocampus of adult cynom...
4,Adult_Human_MTG.pkl,cell types and subtypes (10x-based) from the a...
...,...,...
56,Nuclei_Lung_Airway.pkl,cell populations from snRNA-seq of five locati...
57,PaediatricAdult_COVID19_Airway.pkl,cell types in the airway of paediatric and adu...
58,PaediatricAdult_COVID19_PBMC.pkl,peripheral blood mononuclear cell types of pae...
59,Pan_Fetal_Human.pkl,stromal and immune populations from the human ...
60,Thymus_Allograft_PBMC.pkl,"cell types from cultured, transplanted and con..."

In [ ]:
# check is data is log (Pretty sure it is) and what the dataset has.

In [17]:
adata.X.min(), adata.X.max()

(np.float64(-3.2181900911529984), np.float64(10.0))

In [18]:
adata.uns.keys()

dict_keys(['condition_colors', 'hvg', 'leiden', 'leiden_colors', 'neighbors', 'pca', 'rank_genes_groups', 'sample_colors', 'umap'])

In [19]:
adata.raw

In [ ]:
# Confirm that raw is prescaled values

In [20]:
type(adata.raw.X)

scipy.sparse._csr.csr_matrix

In [21]:
adata.raw.X[:5,:5]

<5x5 sparse matrix of type '<class 'numpy.float32'>'
	with 0 stored elements in Compressed Sparse Row format>

In [ ]:
# Check Number of Genes Stored in Raw.

In [22]:
adata.raw.shape

(47377, 33538)

In [23]:
adata.raw.X[:5,:5]

<5x5 sparse matrix of type '<class 'numpy.float32'>'
	with 0 stored elements in Compressed Sparse Row format>

In [ ]:
"""
The adata.raw was created after HVG, since this is before the reduced size.
Now, I need to figure out if this adata.raw was after Normalization, and log.
I am pretty sure is was, but I need to check as that will change how the pipeline is performed.
I need to see if there are negative numbers in adata.raw, which means it's scaled.
"""

In [24]:
adata.raw.X[:5, :5].toarray()

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]], dtype=float32)

In [25]:
import numpy as np

raw_values = adata.raw.X[:1000].toarray()

print(raw_values.min())
print(raw_values.max())
print(np.mean(raw_values))

0.0
8.789733
0.070122056

In [ ]:
"""
This seems to confirm that adata.raw is after log and norm, but not scaled.

Rather than first analyzsing the post HVG as originally planned.
I am going to just apply the celltype model to the pre HVG dataset, adata.raw.

It was also decided to use two models from celltypist to annotate the adata.raw dataset.
First the vascular annotation for the Smooth Muscle and Endotherial cells.
Than, the Immune-low model for macrophage and NK 
"""

In [ ]:
# Create a copy for annotation

In [26]:
adata_ct = adata.raw.to_adata()

In [ ]:
# Verify

In [27]:
print(adata_ct)
print(type(adata_ct.X))

AnnData object with n_obs × n_vars = 47377 × 33538
    obs: 'sample', 'condition', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_100_genes', 'pct_counts_in_top_200_genes', 'pct_counts_in_top_500_genes', 'total_counts_mt', 'log1p_total_counts_mt', 'pct_counts_mt', 'leiden'
    uns: 'condition_colors', 'hvg', 'leiden', 'leiden_colors', 'neighbors', 'pca', 'rank_genes_groups', 'sample_colors', 'umap'
    obsm: 'X_pca', 'X_umap'
    obsp: 'connectivities', 'distances'
<class 'scipy.sparse._csr.csr_matrix'>

In [ ]:
# Starting the CellTypist Annotation now

In [1]:
# Downloading the Adult_Human_Vascular model

from celltypist import models

models.download_models(
    force_update=False,
    model=["Adult_Human_Vascular.pkl"]
)

D:\Anaconda_redo\Lib\site-packages\celltypist\classifier.py:11: FutureWarning: `__version__` is deprecated, use `importlib.metadata.version('scanpy')` instead
  from scanpy import __version__ as scv
📂 Storing models in C:\Users\scien\.celltypist\data\models
💾 Total models to download: 1
💾 Downloading model [1/1]: Adult_Human_Vascular.pkl

In [2]:
# Verify the model was downloaded

models.models_description()

👉 Detailed model information can be found at `https://www.celltypist.org/models`

,model,description
0,Immune_All_Low.pkl,immune sub-populations combined from 20 tissue...
1,Immune_All_High.pkl,immune populations combined from 20 tissues of...
2,Adult_COVID19_PBMC.pkl,peripheral blood mononuclear cell types from C...
3,Adult_CynomolgusMacaque_Hippocampus.pkl,cell types from the hippocampus of adult cynom...
4,Adult_Human_MTG.pkl,cell types and subtypes (10x-based) from the a...
...,...,...
56,Nuclei_Lung_Airway.pkl,cell populations from snRNA-seq of five locati...
57,PaediatricAdult_COVID19_Airway.pkl,cell types in the airway of paediatric and adu...
58,PaediatricAdult_COVID19_PBMC.pkl,peripheral blood mononuclear cell types of pae...
59,Pan_Fetal_Human.pkl,stromal and immune populations from the human ...
60,Thymus_Allograft_PBMC.pkl,"cell types from cultured, transplanted and con..."

In [ ]:
# Actually verify the model was downloaded

In [3]:
models.get_models()

AttributeError: module 'celltypist.models' has no attribute 'get_models'

In [ ]:
# Try loading the model directly

In [4]:
vascular_model = models.Model.load(
    model="Adult_Human_Vascular.pkl"
)

print(vascular_model)

CellTypist model with 42 cell types and 3521 features
    date: 2024-12-19 16:51:45.315630
    details: vascular populations combined from multiple adult human organs
    source: https://doi.org/10.1038/s41591-024-03376-x
    version: v1
    cell types: adip_cap_ec, aerocyte_ec, ..., ven_smc
    features: SAMD11, HES4, ..., MT-CYB

In [ ]:
# Verify the right names are being used

"""
Models work best when their prfered names are used.
Want to confirm gene names are being used, not numbers ids
"""

In [5]:
print(adata_ct.var_names[:10])

NameError: name 'adata_ct' is not defined

In [ ]:
# Save adata for cell annotation

In [6]:
adata_ct.write(
    r"D:\aer\GSE159677_ct.h5ad"
)

NameError: name 'adata_ct' is not defined

In [7]:
adata_ct = adata.raw.to_adata()

NameError: name 'adata' is not defined

In [ ]:
"""
Webbroser would not respond so the kernal memory is gone.
Will restart Cell annotation in a new notebook
"""